
# from galaxy
- src: coopdevs.sys-admins-role
  version: v0.0.1

- src: geerlingguy.postgresql
  version: 1.3.1

- src: geerlingguy.security
  version: 1.5.0

- src: jdauphant.nginx
  version: v2.11.1

- src: geerlingguy.certbot
  version: 2.0.0

- src: coopdevs.certbot_nginx
  version: 0.0.1
