---
# Sysadmins
sys_admins:

# Tryton vars
venv_path: "/home/tryton/.virtualenvs/tryton"
tryton_path: "/opt/eticom"
tryton_config: "trytond"

# Postgresql vars
tryton_user: eticom
database_name: eticom

