---
# Sysadmins
sys_admins:
  - name: tryton
    ssh_key: "~/.ssh/id_rsa.pub"
    state: present
  - name: "{{ development_user }}"
    ssh_key: "~/.ssh/id_rsa.pub"
    state: present

# Postgresql vars
tryton_user: tryton
database_name: tryton
