---
- name: install software-properties-common
  apt:
    name: software-properties-common
    state: present

- name: Add ppa repository
  command: sudo add-apt-repository ppa:openjdk-r/ppa

- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes

- name: install jre and jdk 7
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - openjdk-7-jre
    - openjdk-7-jdk
