---
- include: install_packages.yml
- include: install_java.yml
- name: install postgres
  become: yes
  include_role:
    name: geerlingguy.postgresql
- include: virtualenv.yml
- include: tryton-config.yml
- include: deploy.yml
- include: service.yml
