---
- name: Add unit service
  become: yes
  template:
    src: tryton.service.j2
    dest: "/etc/systemd/system/tryton.service"
    mode: 774

- name: Enable service
  become: yes
  systemd:
    name: tryton.service
    state: started
    enabled: yes
