---
- name: Check if virtualenv is already created
  stat:
    path: "{{ venv_path }}"
  register: env

- name: Manually create the initial virtualenv
  command: "virtualenv {{ venv_path }} creates={{ venv_path }}"
  when: env.stat.isdir is undefined

- name: copy requirements
  copy:
    src: requirements.txt
    dest: "{{ ansible_env.HOME }}/requirements.txt"

- name: Install requirements
  pip:
    requirements: "{{ ansible_env.HOME }}/requirements.txt"
    virtualenv: "{{ venv_path }}"

- name: Install relatorio
  pip:
    name: relatorio
    version: 0.7.1
    virtualenv: "{{ venv_path }}"
