---
- name: Check if virtualenv is already created
  stat:
    path: "{{ ansible_env.HOME }}/.eticom-venv"
  register: env

- name: Manually create the initial virtualenv
  command: virtualenv "{{ ansible_env.HOME }}/.eticom-venv" creates="{{ ansible_env.HOME }}/.eticom-venv"
  when: env.stat.isdir is undefined

- name: copy requirements
  copy:
    src=requirements.txt
    dest={{ ansible_env.HOME }}/requirements.txt

- name: Install requirements
  pip:
    requirements: "{{ ansible_env.HOME }}/requirements.txt"
    virtualenv: "{{ ansible_env.HOME }}/.eticom-venv"

- name: Install relatorio
  pip:
    name: relatorio
    version: 0.7.1
    virtualenv: "{{ ansible_env.HOME }}/.eticom-venv"
