---
- name: Add environment variables
  become: yes
  template:
    src: tryton.default.j2
    dest: "/etc/default/trytond"
    mode: 644

- name: Add unit service
  become: yes
  template:
    src: tryton.service.j2
    dest: "/etc/systemd/system/tryton@.service"
    mode: 774
  vars:
    tryton_path: "/opt/eticom"


- name: Enable service
  become: yes
  systemd:
    name: tryton.service
    state: started
    enabled: yes
