---

# User name and password for running ansible on host
user: ubuntu

repository: https://hg.tryton.org/trytond
branch: 3.8

# Use correct python2.7 interpeter
ansible_python_interpreter: "/usr/bin/python2.7"

venv_path: "{{ ansible_env.HOME }}/.venv"

postgresql_users:
  - name: "{{ ansible_user }}"
    role_attr_flags: CREATEDB

postgresql_databases:
  - name: "tryton-db"

install_pkgs:
    - git
    - mercurial
    - quilt
    - python-pip
    - python-dev
    - virtualenv
    - libxml2
    - libxml2-dev
    - libxslt1-dev
    - build-essential
    - enchant
    - libffi-dev
    - libssl-dev
    - libldap2-dev
    - libsasl2-dev
    - libpq-dev
    - ttf-mscorefonts-installer
    - unoconv
    - rabbitmq-server
    - nginx
    - libdwarf-dev
    - libelf-dev
    - libunwind-dev
    - ghostscript
    - libssl-dev
    - libffi-dev
    - postgresql-common
    - libpq5
    - libpq-dev
